FROM rootproject/root

USER root

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
wget ca-certificates python gfortran build-essential ghostscript vim libboost-all-dev bzr

WORKDIR /home/hep

ENV MG_VERSION="mg5amcnlo"

RUN bzr branch lp:mg5amcnlo
WORKDIR /home/hep/${MG_VERSION}

ENV ROOTSYS /usr/local
ENV PATH $PATH:$ROOTSYS/bin
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$ROOTSYS/lib

RUN echo install Delphes | /home/hep/${MG_VERSION}/bin/mg5_aMC
RUN echo install ExRootAnalysis | /home/hep/${MG_VERSION}/bin/mg5_aMC
RUN echo install lhapdf6 |  /home/hep/${MG_VERSION}/bin/mg5_aMC
RUN echo install pythia8 | /home/hep/${MG_VERSION}/bin/mg5_aMC
RUN echo install MadAnalysis5 |  /home/hep/${MG_VERSION}/bin/mg5_aMC

# disable autoupdate
# RUN rm /home/hep/${MG_VERSION}/input/.autoupdate

WORKDIR /var/MG_outputs
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/home/hep/${MG_VERSION}/HEPTools/lib/

RUN chmod 777 /home/hep/${MG_VERSION}/models

ADD entry.sh /home/hep/entry.sh
CMD /home/hep/entry.sh
